Service crée + petite réorganisation
CecileGui/frontend-react-todo-list pull request #1
Opened 2020-09-23 14:20 UTC by CecileGui

2020-09-23 23:04 UTC, zakaoai commented on src/TodoApp.js
> +    function getUndoneLength(){
Alors pour moi la fonction ne fait pas ce qu'elle décrit car si 0 tu retourne rien.

Pour améliorer la chose tu pourrait juste retourner la length de ta liste après un filter sur le parametre done

2020-09-24 14:47 UTC, zakaoai requested changes
Voilà le reste de mes commentaires.

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +                        <ListUndone
Alors c'est une question de point de vue mais je suis pas fan de ton découpage
J'aurai plutot vu une séparation en 
- TodosList
- TodoElement

Et que ça soit le TodoElement qui selon ses props fait un rendu done ou pas de la tâche

2020-09-24 14:47 UTC, zakaoai commented on src/todosService.js
> +    return aXios.get('http://localhost:4000/todos/')
Essaye de mettre des constantes, voir importer d'un fichier de conf à coté pour le serveur et le port

2020-09-24 14:47 UTC, zakaoai commented on src/todosService.js
> +    await (aXios.put('http://localhost:4000/todos/' + key, todo)
Utilise plutot un template string qui te donerai un fois le serveur dans des const
`${host}:${port}/todos/${key}`

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +    }, [input])
Ce que tu souhaite faire c'est un simple onMount ?
Dans ce cas il suffit de mettre rien entre les brackets.

Après ça dépend si tu veut qu'à chaque interraction avec la list il y ai un refresh alors il faut voir une autre façon de faire

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +        });
Alors en utilisant find sur ta liste et la destructuration tu aura un code bien plus simple
Tu me dit si tu veut de l'aide pour le faire

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +        await fetch()
On veut faire ces lignes seulement si itemToUpdate est trouvé

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +        await serviceAdd(todo)
Tu ajoute mais la mise à jour de la liste via un fetch n'est pas réalisé. Un oublie ?

2020-09-24 14:47 UTC, zakaoai commented on src/TodoApp.js
> +        return itemsFiltered.length
A la limite plus besoin de variable intermédiaire.

2020-09-24 15:00 UTC, CecileGui commented on src/TodoApp.js
> +    }, [input])
C'était bien un simple onMount, les brackets vides fonctionnent

2020-09-24 15:11 UTC, CecileGui commented on src/TodoApp.js
> +        });
let itemToUpdate = items.find(item => item.key === key)
itemToUpdate.done = !itemToUpdate.done

J'ai fait comme ça

2020-09-24 15:17 UTC, CecileGui commented on src/TodoApp.js
> +        await serviceAdd(todo)
L'ajout déclenche un événement onSubmit qui lance un refresh, du coup un fetch est lancé via useEffect, et donc ce code fonctionne, mais est-ce que c'est propre?

2020-09-24 15:55 UTC, zakaoai commented on src/TodoApp.js
> +        await serviceAdd(todo)
C'est pas plutot l'inverse. ton onSubmit déclanche un ajout. Je voit pas de useEffect qui du coup lance un fetch

2020-09-24 16:12 UTC, CecileGui commented on src/TodoApp.js
> +        await fetch()
`let itemToUpdate = items.find(item => item.key === key)
        if(itemToUpdate){
            itemToUpdate.done = !itemToUpdate.done
            await serviceUpdate(key, itemToUpdate)
            await fetch()
        }else{
            throw 'tried to update a todo but wrong id'
        }`

2020-09-24 16:13 UTC, CecileGui commented on src/TodoApp.js
> +        await fetch()
pas ouf, on peut surement mieux faire pour que tu vois direct les corrections

2020-09-24 16:15 UTC, CecileGui commented on src/TodoApp.js
> +        return itemsFiltered.length
certes

2020-09-25 08:42 UTC, CecileGui commented on src/TodoApp.js
> +        await serviceAdd(todo)
l'événement onSubmit déclenche par défaut un rafraichissement.

2020-09-25 17:26 UTC, zakaoai commented on src/TodoApp.js
> +        await serviceAdd(todo)
Ah oui c'est ça en fait, mais est-ce que tu veut garder ce fonctionnement ou justement qu'il y ait pas de rafraichissement et que tout se fasse en asynchrone ? 
Si tu veut pas de refresh il faut passer l'event et faire un preventDefault() sur celui ci.

2025-09-26 08:38 UTC, closed without merging